modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://marco/Fading_Realms/issues"

[[mods]]
modId="fading_realms"
version="${version}"
displayName="Fading Realms"
logoFile="icon.png"
description='''

'''
[[dependencies.fading_realms]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"
[[dependencies.fading_realms]]
modId="minecraft"
mandatory=true
versionRange="[1.20]"
ordering="NONE"
side="BOTH"
[[dependencies.fading_realms]]
modId="restapi"
mandatory=true
versionRange="[0.9-1.20-Forge]"
ordering="NONE"
side="BOTH"
